In [7]:
#The end specifies the character that needs to be printed after printing the value. 
#By default, it prints a new line character.

import numpy as np

a = np.arange(12)
for b in a:
    print(b, end= ' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [8]:
#Multi dimentional array

products = np.array([['Households','Food&Nutrition','Casmotics','Frozen'],['3','10','5','4'],['15','30','10','10']])
print(products)

[['Households' 'Food&Nutrition' 'Casmotics' 'Frozen']
 ['15' '30' '10' '10']
 ['3' '10' '5' '4']]


In [9]:
# Floatening order row wise

for x in products.flatten():
    print(x)    

Households
Food&Nutrition
Casmotics
Frozen
15
30
10
10
3
10
5
4


In [12]:
# Floatening order colum wise

products = np.array([['Households','Food&Nutrition','Casmotics','Frozen'],['3','10','5','4'],['15','30','10','10']])

for x in products.flatten(order = 'F'):
    print(x)

Households
3
15
Food&Nutrition
10
30
Casmotics
5
10
Frozen
4
10


In [13]:
products = np.array([['Households','Food&Nutrition','Casmotics','Frozen'],['3','10','5','4'],['15','30','10','10']])

for x in products.flatten(order = 'A'):
    print(x)


Households
Food&Nutrition
Casmotics
Frozen
3
10
5
4
15
30
10
10


In [16]:
products = np.array([['Households','Food&Nutrition','Casmotics','Frozen'],['3','10','5','4'],['15','30','10','10']])

for x in products.flatten(order = 'K'):
    print(x)

Households
Food&Nutrition
Casmotics
Frozen
3
10
5
4
15
30
10
10


In [17]:
# nditer
#Iterating a Two-dimensional Array

x = np.arange(15).reshape(5,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [19]:
#Colum iteration 
for i in np.nditer(x, order = 'F'):
    print(i)

0
3
6
9
12
1
4
7
10
13
2
5
8
11
14


In [20]:
# Flags

for i in np.nditer(x, order = 'F', flags=['external_loop'] ):
    print(i)

[ 0  3  6  9 12]
[ 1  4  7 10 13]
[ 2  5  8 11 14]
