In [2]:
#Numbers rows & col operations:
import numpy as np
numbers = np.arange(20).reshape(4,5)
numbers

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
#Calculate sum of cols
numbers.sum(axis = 0)

array([30, 34, 38, 42, 46])

In [4]:
#Calculate sum of rows
numbers.sum(axis = 1)

array([10, 35, 60, 85])

In [7]:
#Prnit min value in array compare by col
numbers.min(axis = 0) 

array([0, 1, 2, 3, 4])

In [8]:
#Prnit min value in array compare by row
numbers.min(axis = 1) 

array([ 0,  5, 10, 15])

In [10]:
#Prnit max value in array compare by col
numbers.max(axis = 0) 

array([15, 16, 17, 18, 19])

In [11]:
#Prnit max value in array compare by row
numbers.max(axis = 1) 

array([ 4,  9, 14, 19])

In [17]:
# Statistical-Functions
Dataset = np.array([[10,14,11,7,9.5,15,19],[8,9,17,14.5,12,18,15.5],
    [15,7.5,11.5,10,10.5,7,11],[11.5,11,9,12,14,12,7.5]])
mean = np.mean(Dataset)
print("Mean value of the given dataset is:")
print(mean)

Mean value of the given dataset is:
11.75


In [18]:
median = np.median(Dataset)
print(median)

11.25
